cache:
  paths:
  - node_modules/

build:
  script:
    - apt-get update
    - apt-get -y install xvfb libgtkextra-dev libgconf2-dev libnss3 libasound2 libxtst-dev libxss1
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - npm install
    - npm test
  only:
    - development