cache:
  paths:
  - node_modules

stages:
  # - test
  - build

variables: {
    VERSION: "cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]'",
    DATE: "date --utc +%FT%T.%3NZ",
    EXE_URL: "https://gitlab.com/herpproject/Sulaiman/-/jobs/$CI_JOB_ID/artifacts/raw/public/Sulaiman-Setup.exe?job=build",
    APPIMAGE_URL: "https://gitlab.com/herpproject/Sulaiman/-/jobs/$CI_JOB_ID/artifacts/raw/public/Sulaiman.AppImage?job=build",
    BUILD_JSON:
      "console.log(JSON.stringify({ build: process.argv[1], commit: process.argv[2], date: process.argv[3], current: process.argv[4], nsis: process.argv[5], appImage: process.argv[6] }));"
}

# test:
#   stage: test
#   script:
#     - npm run test
#   only:
#     - release

build:
  stage: build
  # image: electronuserland/builder:wine
  image: node:slim
  script:
    # - npm install
    # - npm run compile
    # - "echo $(node -e \"$BUILD_JSON\" $BUILD_JSON_ARGS) >> build.json"
    # - npx electron-builder --win NSIS
    # - "PACKAGE_TYPE='appImage' && rm build.json && echo $($BUILD_JSON) >> build.json"
    # - npx electron-builder --linux AppImage
    - "echo $(node -e \"$BUILD_JSON\" $($VERSION) $CI_COMMIT_SHA $($DATE) $PACKAGE_TYPE $EXE_URL $APPIMAGE_URL) >> build.json"
  artifacts:
    expire_in: 6 mos
    paths:
      # - public/Sulaiman-Setup.exe
      # - public/Sulaiman.AppImage
      - build.json
  only:
    - release