cache:
  paths:
  - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - echo "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm install" | sh
    - npm test
  only:
    - development
  tags:
    - arch
    - linux
    - 64bit

deploy:
  stage: deploy
  image: node:slim
  script:
    - echo "hello world"
  only:
    - development
  tags:
    - docker