image: node:slim

# cache:
#   paths:
#   - node_modules/

build:
  script:
    - apt-get update
    - apt-get -y install libgtkextra-dev libgconf2-dev libnss3 libasound2 libxtst-dev libxss1
    - npm install
    - npm run test2
    - npm run test3
  only:
    - development