cache:
  paths:
  - node_modules

variables: {
    EXE_URL: "https://gitlab.com/herpproject/Sulaiman/-/jobs/$CI_JOB_ID/artifacts/raw/public/Sulaiman-Setup.exe?job=build",
    APPIMAGE_URL: "https://gitlab.com/herpproject/Sulaiman/-/jobs/$CI_JOB_ID/artifacts/raw/public/Sulaiman.AppImage?job=build",
    URLS: "$EXE_URL $APPIMAGE_URL",
    BUILD_JSON:
      "console.log(JSON.stringify({ build: process.argv[1], commit: process.argv[2], date: process.argv[3], package: process.argv[4] || null, nsis: process.argv[5], appImage: process.argv[6] }));"
}

stages:
  # - test
  - build

# test:
#   stage: test
#   script:
#     - npm run test
#   only:
#     - release

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - "VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[\",]//g' | tr -d '[[:space:]]')"
    - "DATE=$(date --utc +%FT%T.%3NZ)"

    - npm install
    - npm run compile

    - "echo $(node -e \"$BUILD_JSON\" $VERSION $CI_COMMIT_SHA $DATE \"nsis\" $URLS) >> build.json"
    - npx electron-builder --win NSIS

    - "rm build.json && echo $(node -e \"$BUILD_JSON\" $VERSION $CI_COMMIT_SHA $DATE \"appImage\" $URLS) >> build.json"
    - npx electron-builder --linux AppImage

    - "rm build.json && echo $(node -e \"$BUILD_JSON\" $VERSION $CI_COMMIT_SHA $DATE \"\" $URLS) >> build.json"
  artifacts:
    expire_in: 6 mos
    paths:
      - public/Sulaiman-Setup.exe
      - public/Sulaiman.AppImage
      - build.json
  only:
    - release