cache:
  paths:
  - node_modules

stages:
  # - test
  - build

# test:
#   stage: test
#   script:
#     - npm run test
#   only:
#     - release

build:
  stage: deploy
  image: node:slim
  script:
    - sudo apt-get update
    - sudo apt-get install -y wine
    - npm run compile
    - npx electron-builder --win NSIS --linux AppImage
  artifacts:
    expire_in: 6 mos
    paths:
      - public/Sulaiman Setup.exe
      - public/Sulaiman.AppImage
  only:
    - release