cache:
  paths:
  - node_modules
  - /.cache/electron
  - /.cache/electron-builder

# variables: {
#  ELECTRON_CACHE: '/.cache/electron',
#  ELECTRON_BUILDER_CACHE: '/.cache/electron-builder'
# }

stages:
  # - test
  - build

# test:
#   stage: test
#   script:
#     - npm run test
#   only:
#     - release

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - npm install
    - npm run compile
    - npx electron-builder --win NSIS --linux AppImage
  artifacts:
    expire_in: 6 mos
    paths:
      - public
  only:
    - release