cache:
  paths:
  - node_modules/

build:
  script:
    - echo "export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true && npm install" | sudo sh
    - npm test
  only:
    - development
  tags:
    - arch
    - linux
    - 64bit