cache:
  paths:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

variables: {
 ELECTRON_BUILDER_CACHE: '$HOME/.cache/electron-builder',
 ELECTRON_CACHE: '$HOME/.cache/electron'
}

stages:
  # - test
  - build

# test:
#   stage: test
#   script:
#     - npm run test
#   only:
#     - release

build:
  stage: build
  image: electronuserland/builder:wine
  script:
    - npm install
    - npm run compile
    - npx electron-builder --win NSIS --linux AppImage
  artifacts:
    expire_in: 6 mos
    paths:
      - public/Sulaiman Setup.exe
      - public/Sulaiman.AppImage
  only:
    - release